# Generated by Django 2.0.13 on 2022-11-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='isImportant',
        ),
    ]
