# Generated by Django 4.1.3 on 2022-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_remove_notice_isimportant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.FileField(upload_to='noticeContent/%Y/%m/%d'),
        ),
    ]
